name: "Generate Release Notes"
description: "Generates beautiful, structured release notes for multi-platform releases"
author: "Alberto Cavalcante"

branding:
  icon: "file-text"
  color: "blue"

inputs:
  version:
    description: "Release version (e.g., v0.1.0 or nightly)"
    required: true
  assets-dir:
    description: "Directory containing release assets"
    required: true
    default: "release-assets"
  project-name:
    description: "Project name for display"
    required: true
  project-description:
    description: "Short project description"
    required: false
    default: ""
  repository:
    description: "Repository in owner/repo format"
    required: false
    default: ${{ github.repository }}
  is-prerelease:
    description: "Whether this is a prerelease (nightly, rc, etc.)"
    required: false
    default: "false"
  build-status:
    description: "JSON object with build job results"
    required: false
    default: "{}"
  workflow-run-id:
    description: "Workflow run ID for linking to failed builds"
    required: false
    default: ${{ github.run_id }}
  template:
    description: "Path to custom Handlebars template (optional)"
    required: false

outputs:
  release-notes:
    description: "Generated release notes markdown"
  release-notes-file:
    description: "Path to generated release notes file"
  assets-json:
    description: "JSON object with all discovered assets and their metadata (platform, sha256, size, url)"
  checksums-json:
    description: "JSON object mapping filenames to SHA256 checksums"
  homebrew-assets:
    description: "JSON object formatted for update-homebrew-tap action consumption"

runs:
  using: "node20"
  main: "dist/index.js"
